### ISSUE TITLE
Can you write the document in English, thank you

### ISSUE THREAD

**Issue by leonshi001** [kasworld/goguelike#1]
Can you write the document in English, thank you

**Comment by kasworld** [comment]
I am not good at english. 
How about try google translate.

Readme.md 
https://translate.google.co.kr/translate?sl=ko&tl=en&u=https%3A%2F%2Fraw.githubusercontent.com%2Fkasworld%2Fgoguelike%2Fmaster%2FREADME.md

Install.md 
https://translate.google.co.kr/translate?sl=ko&tl=en&u=https://raw.githubusercontent.com/kasworld/goguelike/master/INSTALL.md
